stages:
  - test
  - deploy

test:
  stage: test
  script: echo "Running tests"

deploy:
  stage: deploy
  script:
    - yarn install
    - node --harmony index.js
  environment:
    name: production
